### ISSUE TITLE
Support for devices in HostConfig ( docker )

### ISSUE THREAD

**Issue by ScarlettGatelyClark** [blue-systems/pangea-tooling#11]
I am trying to merge aci tooling in and I have hit a blocker. I need 

  'HostConfig' => {
        'Binds' => [
          Dir.pwd + ":/in",
          Dir.pwd + "/app:/app",
          Dir.pwd + "/appimage:/appimage",
          '/root/.gnupg:/root/.gnupg'
        ],
        'UsernsMode' => 'host',
        'Privileged' => true,
        'Devices' => [
          'PathOnHost' => '/dev/fuse',
          'PathInContainer' => '/dev/fuse',
          'CgroupPermissions' => 'mrw'
        ]
      }

The binds / usernsMode / privileged are already covered. The Devices however have no option :( 
I can try to add the support myself, but if someone more familiar with the code could whip something up, I would be ever so greatful.

**Comment by apachelogger** [comment]
I don't even know what class you are talking about.

If it is containment... you can pass arguments to run(). Looking at the code you'll have to convert contain() to use a deep_merge rather than a merge though

**Comment by ScarlettGatelyClark** [comment]
yes, containment. I will try that. thanks!
