### ISSUE TITLE
KDE neon ISOs should have kde-baseapps-bin and desktop-file-utils

### ISSUE THREAD

**Issue by probonopd** [blue-systems/pangea-tooling#4]
Not entirely sure where this should go, but I am deeply missing the packages `kde-baseapps-bin` and `desktop-file-utils` in the default installation of KDE neon. They contain elementary stuff like `kdialog` and `desktop-file-validate` which is present on almost any other distribution that comes with Plasma.

Besides, many AppImages use them for desktop integration.

Could they be added to `nci/imager/config-hooks-neon/20_package_list.sh` or `nci/imager/build.sh`?

**Comment by jriddell** [comment]
kde-baseapps-bin is kdelibs4 which we don't want to include in Neon, needs the frameworks branch merged into master
desktop-file-utils seems harmless enough but what's it needed for?

**Comment by jriddell** [comment]
appimage desktopintegration scripts use desktop-file-utils  says scarlett

**Comment by probonopd** [comment]
Yes, `desktop-file-utils` are assumed to be there on all target systems by the AppImageKit [desktopintegration](https://github.com/probonopd/AppImageKit/blob/master/desktopintegration) script (and indeed are on the vast majority of systems but not in KDE neon).

**Comment by jriddell** [comment]
desktop-file-utils added to ISOs
I don't want to add kdelibs4 stuff to the images, kde-baseapps has been ported to master so we can update packaging neon:applications/kde-baseapps for that and add to Neon/unstable

**Comment by probonopd** [comment]
Thanks. Hopefully there will be a pure-Qt or KF5 version of zenity/kdialog.
