### ISSUE TITLE
ARMv8 support

### ISSUE THREAD

**Issue by shadeslayer** [blue-systems/pangea-tooling#9]
I'll be working on ARMv8 support soon and currently the tooling fails to deploy

http://mobile.neon.pangea.pub:8080/job/mgmt_docker/label=147.75.105.102/1661/console

This seems to be due to a outdated ffi and there's a PR to update ffi here https://github.com/ffi/ffi/pull/466

Would it be alright if we forked a ffi release and used it in the tooling?

**Comment by shadeslayer** [comment]
@bhush9 @jriddell @ScarlettGatelyClark  @apachelogger

**Comment by bhush9** [comment]
I've no objections..
